name: BUILD_AND_DEPLOYMENT

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Authentication Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Create build env
        run: |
          printf "\
          NEXT_TELEMETRY_DISABLED=1\n\
          NODE_ENV=${{secrets.NODE_ENV}} \n\       
          NEXT_PUBLIC_URL=${{secrets.NEXT_PUBLIC_URL}} \n\      
          NEXTAUTH_URL=${{secrets.NEXTAUTH_URL}} \n\    
          NEXTAUTH_SECRET=${{secrets.NEXTAUTH_SECRET}} \n\      
          DATABASE_URL=${{secrets.DATABASE_URL}} \n\     
          S3_ACCESS_KEY=${{secrets.S3_ACCESS_KEY}} \n\       
          S3_SECRET_ACCESS_KEY=${{secrets.S3_SECRET_ACCESS_KEY}} \n\       
          S3_REGION=${{secrets.S3_REGION}} \n\      
          S3_BUCKET_NAME=${{secrets.S3_BUCKET_NAME}} \n\        
          " > .env
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: Dockerfile.build
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/simple-tuwiter:latest
          labels: ${{ steps.meta.outputs.labels }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.AWS_APPLICATION_NAME }}
          environment_name: ${{ secrets.AWS_ENVIRONMENT_NAME }}
          version_label: "ver-${{ github.sha }}"
          region: ${{secrets.S3_REGION}}
          deployment_package: deploy.zip
